### ISSUE TITLE
[Feature Request] It would be nice if we could list all the existing settings.

### ISSUE THREAD

**Issue by jonathanantoine** [jamesmontemagno/SettingsPlugin#39] opened 2017-01-13 11:20 UTC
## Feature Request:
It would be nice if we could list all the existing settings. 
If we want to remove only some of them for instance.

`foreach (var kVp in CrossSettings.Current.Values)`
`{`
`    var key = kVp.Key;`
`    var value = kVp.Value;`
`}`

Thank you !

**Comment by Ingenator** [comment] 2017-03-14 00:46
I need this one too!!

**Comment by jamesmontemagno** [comment] 2017-05-30 18:21
Duplicate of #10

**Closed as completed by jamesmontemagno** 2017-05-30 18:21 UTC
Labels: feature
