### ISSUE TITLE
Issue with types Guid and DateTime

### ISSUE THREAD

**Issue by avinash-ramireddy** [jamesmontemagno/SettingsPlugin#79] opened 2017-07-04 08:05 UTC
Hi,
I was trying to pass guid using settings.SelectedItemId but it's returning exception

 **_FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)._**

and issue with datetime is that when I set datetime it's subtracting 5.30hrs in settings.SelectedDate contain less time(530hrs) that what is passed.

Update:
I just read documentation and found that date part is correct

**Comment by jamesmontemagno** [comment] 2017-07-04 15:58
What does your "SelectedItemIndex look like"... what platform? 

Here is a template that you deleted... fill it in:

If you are creating an issue for a BUG please fill out this information. If you are asking a question or requesting a feature you can delete the sections below. 

**Failure to fill out this information will result in this issue being closed.** If you post a full stack trace in a bug it will be closed, please post it to http://gist.github.com and then post the link here.

## Bug Information

Version Number of Plugin:
Device Tested On:
Simulator Tested On:
Version of VS: 
Version of Xamarin:
Versions of other things you are using:

### Steps to reproduce the Behavior

### Expected Behavior

### Actual Behavior

### Code snippet

### Screenshots

**Comment by avinash-ramireddy** [comment] 2017-07-04 17:16
I was actually working on android at that moment.
My SelectedItemId is Guid 
I will try to create a way to reproduce the issue as it was not happening all the time.


In the mean time,can you help me with the date part. I am setting some date and I want to fetch as it is.How can I do that?

**Comment by jamesmontemagno** [comment] 2017-07-04 18:38
It saves all dates as UTC, so you will want to convert it back.

**Comment by jamesmontemagno** [comment] 2017-07-18 17:22
Closing out due to UTC documented and lack of info on GUID issue.

**Closed as completed by jamesmontemagno** 2017-07-18 17:22 UTC
